server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:}
app.frontend.url=https://jewellery-frontend-12de9ec337a7.herokuapp.com/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

aws.access-key=${AWS_ACCESS_KEY_ID:}
aws.secret-key=${AWS_SECRET_ACCESS_KEY:}
aws.region=${AWS_REGION:}
aws.s3.bucket=${AWS_S3_BUCKET:}


spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:50MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:50MB}